require "file_utils"

require "./parser"

class LibFilesWriter
  @parser : Parser

  def initialize(@parser)
    @output_dir = Path.new(__DIR__, "../src/blend2d/lib_blend2d")
  end

  def write_files
    FileUtils.mkdir_p @output_dir

    @parser.files.each do |c_filename, blfile|
      filename = c_filename.rchop(".h") + ".cr"
      write_file(@output_dir.join(filename), blfile)
    end
  end

  def write_file(path, blfile)
    contents = String.build do |str|
      str << <<-HEADER
        # This file is automatically generated and should not be manually edited

        module Blend2D
          @[Link("blend2d")]
          lib LibBlend2D

        HEADER

      blfile.typedefs.each { |t| str << t << "\n" }
      str << "\n"
      blfile.functions.each { |f| str << f << "\n" }
      str << "\n"
      blfile.enums.each { |e| str << e << "\n\n" }
      blfile.structs.each { |s| str << s << "\n\n" }

      # Missing from parsed structs
      if path.basename == "object.cr"
        str << <<-IMPL
            struct BLObjectImpl
              _dummy : Void*
            end

        IMPL
      end

      str << <<-FOOTER
          end
        end
        FOOTER
    end

    File.write(path, contents)
  end
end
