# This file is automatically generated and should not be manually edited

module Blend2D
  @[Link("blend2d")]
  lib LibBlend2D
    alias BLResult = BLResultCode
    alias BLTag = UInt32
    alias BLUniqueId = LibC::ULong
    alias BLUnknown = Void
    alias BLDebugMessageSinkFunc = (UInt8*, Int32, Void*) -> Void*
    alias BLDataView = BLArrayView

    fun blTraceError(result : BLResult) : BLResult
    fun blRuntimeAssertionFailure(file : UInt8*, line : Int32, msg : UInt8*) : Void

    enum BLResultCode : UInt32
      Success                        =     0
      ErrorStartIndex                = 65536
      ErrorOutOfMemory               = 65536
      ErrorInvalidValue              = 65537
      ErrorInvalidState              = 65538
      ErrorInvalidHandle             = 65539
      ErrorInvalidConversion         = 65540
      ErrorOverflow                  = 65541
      ErrorNotInitialized            = 65542
      ErrorNotImplemented            = 65543
      ErrorNotPermitted              = 65544
      ErrorIo                        = 65545
      ErrorBusy                      = 65546
      ErrorInterrupted               = 65547
      ErrorTryAgain                  = 65548
      ErrorTimedOut                  = 65549
      ErrorBrokenPipe                = 65550
      ErrorInvalidSeek               = 65551
      ErrorSymlinkLoop               = 65552
      ErrorFileTooLarge              = 65553
      ErrorAlreadyExists             = 65554
      ErrorAccessDenied              = 65555
      ErrorMediaChanged              = 65556
      ErrorReadOnlyFs                = 65557
      ErrorNoDevice                  = 65558
      ErrorNoEntry                   = 65559
      ErrorNoMedia                   = 65560
      ErrorNoMoreData                = 65561
      ErrorNoMoreFiles               = 65562
      ErrorNoSpaceLeft               = 65563
      ErrorNotEmpty                  = 65564
      ErrorNotFile                   = 65565
      ErrorNotDirectory              = 65566
      ErrorNotSameDevice             = 65567
      ErrorNotBlockDevice            = 65568
      ErrorInvalidFileName           = 65569
      ErrorFileNameTooLong           = 65570
      ErrorTooManyOpenFiles          = 65571
      ErrorTooManyOpenFilesByOs      = 65572
      ErrorTooManyLinks              = 65573
      ErrorTooManyThreads            = 65574
      ErrorThreadPoolExhausted       = 65575
      ErrorFileEmpty                 = 65576
      ErrorOpenFailed                = 65577
      ErrorNotRootDevice             = 65578
      ErrorUnknownSystemError        = 65579
      ErrorInvalidAlignment          = 65580
      ErrorInvalidSignature          = 65581
      ErrorInvalidData               = 65582
      ErrorInvalidString             = 65583
      ErrorInvalidKey                = 65584
      ErrorDataTruncated             = 65585
      ErrorDataTooLarge              = 65586
      ErrorDecompressionFailed       = 65587
      ErrorInvalidGeometry           = 65588
      ErrorNoMatchingVertex          = 65589
      ErrorInvalidCreateFlags        = 65590
      ErrorNoMatchingCookie          = 65591
      ErrorNoStatesToRestore         = 65592
      ErrorTooManySavedStates        = 65593
      ErrorImageTooLarge             = 65594
      ErrorImageNoMatchingCodec      = 65595
      ErrorImageUnknownFileFormat    = 65596
      ErrorImageDecoderNotProvided   = 65597
      ErrorImageEncoderNotProvided   = 65598
      ErrorPngMultipleIhdr           = 65599
      ErrorPngInvalidIdat            = 65600
      ErrorPngInvalidIend            = 65601
      ErrorPngInvalidPlte            = 65602
      ErrorPngInvalidTrns            = 65603
      ErrorPngInvalidFilter          = 65604
      ErrorJpegUnsupportedFeature    = 65605
      ErrorJpegInvalidSos            = 65606
      ErrorJpegInvalidSof            = 65607
      ErrorJpegMultipleSof           = 65608
      ErrorJpegUnsupportedSof        = 65609
      ErrorFontNotInitialized        = 65610
      ErrorFontNoMatch               = 65611
      ErrorFontNoCharacterMapping    = 65612
      ErrorFontMissingImportantTable = 65613
      ErrorFontFeatureNotAvailable   = 65614
      ErrorFontCffInvalidData        = 65615
      ErrorFontProgramTerminated     = 65616
      ErrorGlyphSubstitutionTooLarge = 65617
      ErrorInvalidGlyph              = 65618

      def success_or_raise
        return if self == Success
        raise self.to_s
      end
    end

    enum BLByteOrder : UInt32
      LE      = 0
      BE      = 1
      Native  = 0
      Swapped = 1
    end

    enum BLDataAccessFlags : UInt32
      NoFlags = 0
      Read    = 1
      Write   = 2
      RW      = 3
    end

    enum BLDataSourceType : UInt32
      None   = 0
      Memory = 1
      File   = 2
      Custom = 3
    end

    enum BLModifyOp : UInt32
      AssignFit  = 0
      AssignGrow = 1
      AppendFit  = 2
      AppendGrow = 3
    end

    enum BLBooleanOp : UInt32
      Copy   = 0
      And    = 1
      Or     = 2
      Xor    = 3
      AndNot = 4
      NotAnd = 5
    end

    enum BLExtendMode : UInt32
      Pad              = 0
      Repeat           = 1
      Reflect          = 2
      PadXPadY         = 0
      PadXRepeatY      = 3
      PadXReflectY     = 4
      RepeatXRepeatY   = 1
      RepeatXPadY      = 5
      RepeatXReflectY  = 6
      ReflectXReflectY = 2
      ReflectXPadY     = 7
      ReflectXRepeatY  = 8
    end

    enum BLTextEncoding : UInt32
      UTF8   = 0
      UTF16  = 1
      UTF32  = 2
      Latin1 = 3
      Wchar  = 4
    end

    struct BLRange
      start : Int32
      _end : Int32
    end

    struct BLArrayView
      data : Void*
      size : Int32
    end

    struct BLStringView
      data : UInt8*
      size : Int32
    end
  end
end
