# This file is automatically generated and should not be manually edited

module Blend2D
  @[Link("blend2d")]
  lib LibBlend2D
    fun blBitSetInit(self : BLBitSetCore*) : BLResult
    fun blBitSetInitMove(self : BLBitSetCore*, other : BLBitSetCore*) : BLResult
    fun blBitSetInitWeak(self : BLBitSetCore*, other : BLBitSetCore*) : BLResult
    fun blBitSetInitRange(self : BLBitSetCore*, start_bit : UInt32, end_bit : UInt32) : BLResult
    fun blBitSetDestroy(self : BLBitSetCore*) : BLResult
    fun blBitSetReset(self : BLBitSetCore*) : BLResult
    fun blBitSetAssignMove(self : BLBitSetCore*, other : BLBitSetCore*) : BLResult
    fun blBitSetAssignWeak(self : BLBitSetCore*, other : BLBitSetCore*) : BLResult
    fun blBitSetAssignDeep(self : BLBitSetCore*, other : BLBitSetCore*) : BLResult
    fun blBitSetAssignRange(self : BLBitSetCore*, start_bit : UInt32, end_bit : UInt32) : BLResult
    fun blBitSetAssignWords(self : BLBitSetCore*, start_word : UInt32, word_data : UInt32*, word_count : UInt32) : BLResult
    fun blBitSetIsEmpty(self : BLBitSetCore*) : Bool
    fun blBitSetGetData(self : BLBitSetCore*, out : BLBitSetData*) : BLResult
    fun blBitSetGetSegmentCount(self : BLBitSetCore*) : UInt32
    fun blBitSetGetSegmentCapacity(self : BLBitSetCore*) : UInt32
    fun blBitSetGetCardinality(self : BLBitSetCore*) : UInt32
    fun blBitSetGetCardinalityInRange(self : BLBitSetCore*, start_bit : UInt32, end_bit : UInt32) : UInt32
    fun blBitSetHasBit(self : BLBitSetCore*, bit_index : UInt32) : Bool
    fun blBitSetHasBitsInRange(self : BLBitSetCore*, start_bit : UInt32, end_bit : UInt32) : Bool
    fun blBitSetSubsumes(a : BLBitSetCore*, b : BLBitSetCore*) : Bool
    fun blBitSetIntersects(a : BLBitSetCore*, b : BLBitSetCore*) : Bool
    fun blBitSetGetRange(self : BLBitSetCore*, start_out : UInt32*, end_out : UInt32*) : Bool
    fun blBitSetEquals(a : BLBitSetCore*, b : BLBitSetCore*) : Bool
    fun blBitSetCompare(a : BLBitSetCore*, b : BLBitSetCore*) : Int32
    fun blBitSetClear(self : BLBitSetCore*) : BLResult
    fun blBitSetShrink(self : BLBitSetCore*) : BLResult
    fun blBitSetOptimize(self : BLBitSetCore*) : BLResult
    fun blBitSetChop(self : BLBitSetCore*, start_bit : UInt32, end_bit : UInt32) : BLResult
    fun blBitSetAddBit(self : BLBitSetCore*, bit_index : UInt32) : BLResult
    fun blBitSetAddRange(self : BLBitSetCore*, range_start_bit : UInt32, range_end_bit : UInt32) : BLResult
    fun blBitSetAddWords(self : BLBitSetCore*, start_word : UInt32, word_data : UInt32*, word_count : UInt32) : BLResult
    fun blBitSetClearBit(self : BLBitSetCore*, bit_index : UInt32) : BLResult
    fun blBitSetClearRange(self : BLBitSetCore*, range_start_bit : UInt32, range_end_bit : UInt32) : BLResult
    fun blBitSetBuilderCommit(self : BLBitSetCore*, builder : BLBitSetBuilderCore*, new_area_index : UInt32) : BLResult
    fun blBitSetBuilderAddRange(self : BLBitSetCore*, builder : BLBitSetBuilderCore*, start_bit : UInt32, end_bit : UInt32) : BLResult

    enum BLBitSetConstants : UInt32
      InvalidIndex     = 4294967295
      RangeMask        = 2147483648
      SegmentWordCount =          4
    end

    struct BLBitSetSegment
      _start_word : UInt32
      _data : UInt32[4]
    end

    struct BLBitSetData
      segment_data : BLBitSetSegment*
      segment_count : UInt32
      sso_segments : BLBitSetSegment[3]
    end

    struct BLBitSetCore
      _d : BLBitSetImpl*
    end

    struct BLBitSetBuilderCore
      _area_shift : UInt32
      _area_index : UInt32
    end

    struct BLBitSetImpl
      segment_count : UInt32
      segment_capacity : UInt32
    end
  end
end
