# This file is automatically generated and should not be manually edited

module Blend2D
  @[Link("blend2d")]
  lib LibBlend2D
    fun blContextInit(self : BLContextCore*) : BLResult
    fun blContextInitMove(self : BLContextCore*, other : BLContextCore*) : BLResult
    fun blContextInitWeak(self : BLContextCore*, other : BLContextCore*) : BLResult
    fun blContextInitAs(self : BLContextCore*, image : BLImageCore*, cci : BLContextCreateInfo*) : BLResult
    fun blContextDestroy(self : BLContextCore*) : BLResult
    fun blContextReset(self : BLContextCore*) : BLResult
    fun blContextAssignMove(self : BLContextCore*, other : BLContextCore*) : BLResult
    fun blContextAssignWeak(self : BLContextCore*, other : BLContextCore*) : BLResult
    fun blContextGetType(self : BLContextCore*) : BLContextType
    fun blContextGetTargetSize(self : BLContextCore*, target_size_out : BLSize*) : BLResult
    fun blContextGetTargetImage(self : BLContextCore*) : BLImageCore*
    fun blContextBegin(self : BLContextCore*, image : BLImageCore*, cci : BLContextCreateInfo*) : BLResult
    fun blContextEnd(self : BLContextCore*) : BLResult
    fun blContextFlush(self : BLContextCore*, flags : BLContextFlushFlags) : BLResult
    fun blContextSave(self : BLContextCore*, cookie : BLContextCookie*) : BLResult
    fun blContextRestore(self : BLContextCore*, cookie : BLContextCookie*) : BLResult
    fun blContextGetMetaTransform(self : BLContextCore*, transform_out : BLMatrix2D*) : BLResult
    fun blContextGetUserTransform(self : BLContextCore*, transform_out : BLMatrix2D*) : BLResult
    fun blContextGetFinalTransform(self : BLContextCore*, transform_out : BLMatrix2D*) : BLResult
    fun blContextUserToMeta(self : BLContextCore*) : BLResult
    fun blContextApplyTransformOp(self : BLContextCore*, op_type : BLTransformOp, op_data : Void*) : BLResult
    fun blContextGetHint(self : BLContextCore*, hint_type : BLContextHint) : UInt32
    fun blContextSetHint(self : BLContextCore*, hint_type : BLContextHint, value : UInt32) : BLResult
    fun blContextGetHints(self : BLContextCore*, hints_out : BLContextHints*) : BLResult
    fun blContextSetHints(self : BLContextCore*, hints : BLContextHints*) : BLResult
    fun blContextSetFlattenMode(self : BLContextCore*, mode : BLFlattenMode) : BLResult
    fun blContextSetFlattenTolerance(self : BLContextCore*, tolerance : Float64) : BLResult
    fun blContextSetApproximationOptions(self : BLContextCore*, options : BLApproximationOptions*) : BLResult
    fun blContextGetFillStyle(self : BLContextCore*, style_out : BLVarCore*) : BLResult
    fun blContextGetTransformedFillStyle(self : BLContextCore*, style_out : BLVarCore*) : BLResult
    fun blContextSetFillStyle(self : BLContextCore*, style : BLUnknown*) : BLResult
    fun blContextSetFillStyleWithMode(self : BLContextCore*, style : BLUnknown*, transform_mode : BLContextStyleTransformMode) : BLResult
    fun blContextSetFillStyleRgba(self : BLContextCore*, rgba : BLRgba*) : BLResult
    fun blContextSetFillStyleRgba32(self : BLContextCore*, rgba32 : UInt32) : BLResult
    fun blContextSetFillStyleRgba64(self : BLContextCore*, rgba64 : LibC::ULong) : BLResult
    fun blContextDisableFillStyle(self : BLContextCore*) : BLResult
    fun blContextGetFillAlpha(self : BLContextCore*) : Float64
    fun blContextSetFillAlpha(self : BLContextCore*, alpha : Float64) : BLResult
    fun blContextGetStrokeStyle(self : BLContextCore*, style_out : BLVarCore*) : BLResult
    fun blContextGetTransformedStrokeStyle(self : BLContextCore*, style_out : BLVarCore*) : BLResult
    fun blContextSetStrokeStyle(self : BLContextCore*, style : BLUnknown*) : BLResult
    fun blContextSetStrokeStyleWithMode(self : BLContextCore*, style : BLUnknown*, transform_mode : BLContextStyleTransformMode) : BLResult
    fun blContextSetStrokeStyleRgba(self : BLContextCore*, rgba : BLRgba*) : BLResult
    fun blContextSetStrokeStyleRgba32(self : BLContextCore*, rgba32 : UInt32) : BLResult
    fun blContextSetStrokeStyleRgba64(self : BLContextCore*, rgba64 : LibC::ULong) : BLResult
    fun blContextDisableStrokeStyle(self : BLContextCore*) : BLResult
    fun blContextGetStrokeAlpha(self : BLContextCore*) : Float64
    fun blContextSetStrokeAlpha(self : BLContextCore*, alpha : Float64) : BLResult
    fun blContextSwapStyles(self : BLContextCore*, mode : BLContextStyleSwapMode) : BLResult
    fun blContextGetGlobalAlpha(self : BLContextCore*) : Float64
    fun blContextSetGlobalAlpha(self : BLContextCore*, alpha : Float64) : BLResult
    fun blContextGetCompOp(self : BLContextCore*) : BLCompOp
    fun blContextSetCompOp(self : BLContextCore*, comp_op : BLCompOp) : BLResult
    fun blContextGetFillRule(self : BLContextCore*) : BLFillRule
    fun blContextSetFillRule(self : BLContextCore*, fill_rule : BLFillRule) : BLResult
    fun blContextGetStrokeWidth(self : BLContextCore*) : Float64
    fun blContextSetStrokeWidth(self : BLContextCore*, width : Float64) : BLResult
    fun blContextGetStrokeMiterLimit(self : BLContextCore*) : Float64
    fun blContextSetStrokeMiterLimit(self : BLContextCore*, miter_limit : Float64) : BLResult
    fun blContextGetStrokeCap(self : BLContextCore*, position : BLStrokeCapPosition) : BLStrokeCap
    fun blContextSetStrokeCap(self : BLContextCore*, position : BLStrokeCapPosition, stroke_cap : BLStrokeCap) : BLResult
    fun blContextSetStrokeCaps(self : BLContextCore*, stroke_cap : BLStrokeCap) : BLResult
    fun blContextGetStrokeJoin(self : BLContextCore*) : BLStrokeJoin
    fun blContextSetStrokeJoin(self : BLContextCore*, stroke_join : BLStrokeJoin) : BLResult
    fun blContextGetStrokeTransformOrder(self : BLContextCore*) : BLStrokeTransformOrder
    fun blContextSetStrokeTransformOrder(self : BLContextCore*, transform_order : BLStrokeTransformOrder) : BLResult
    fun blContextGetStrokeDashOffset(self : BLContextCore*) : Float64
    fun blContextSetStrokeDashOffset(self : BLContextCore*, dash_offset : Float64) : BLResult
    fun blContextGetStrokeDashArray(self : BLContextCore*, dash_array_out : BLArrayCore*) : BLResult
    fun blContextSetStrokeDashArray(self : BLContextCore*, dash_array : BLArrayCore*) : BLResult
    fun blContextGetStrokeOptions(self : BLContextCore*, options : BLStrokeOptionsCore*) : BLResult
    fun blContextSetStrokeOptions(self : BLContextCore*, options : BLStrokeOptionsCore*) : BLResult
    fun blContextClipToRectI(self : BLContextCore*, rect : BLRectI*) : BLResult
    fun blContextClipToRectD(self : BLContextCore*, rect : BLRect*) : BLResult
    fun blContextRestoreClipping(self : BLContextCore*) : BLResult
    fun blContextClearAll(self : BLContextCore*) : BLResult
    fun blContextClearRectI(self : BLContextCore*, rect : BLRectI*) : BLResult
    fun blContextClearRectD(self : BLContextCore*, rect : BLRect*) : BLResult
    fun blContextFillAll(self : BLContextCore*) : BLResult
    fun blContextFillAllRgba32(self : BLContextCore*, rgba32 : UInt32) : BLResult
    fun blContextFillAllRgba64(self : BLContextCore*, rgba64 : LibC::ULong) : BLResult
    fun blContextFillAllExt(self : BLContextCore*, style : BLUnknown*) : BLResult
    fun blContextFillRectI(self : BLContextCore*, rect : BLRectI*) : BLResult
    fun blContextFillRectIRgba32(self : BLContextCore*, rect : BLRectI*, rgba32 : UInt32) : BLResult
    fun blContextFillRectIRgba64(self : BLContextCore*, rect : BLRectI*, rgba64 : LibC::ULong) : BLResult
    fun blContextFillRectIExt(self : BLContextCore*, rect : BLRectI*, style : BLUnknown*) : BLResult
    fun blContextFillRectD(self : BLContextCore*, rect : BLRect*) : BLResult
    fun blContextFillRectDRgba32(self : BLContextCore*, rect : BLRect*, rgba32 : UInt32) : BLResult
    fun blContextFillRectDRgba64(self : BLContextCore*, rect : BLRect*, rgba64 : LibC::ULong) : BLResult
    fun blContextFillRectDExt(self : BLContextCore*, rect : BLRect*, style : BLUnknown*) : BLResult
    fun blContextFillPathD(self : BLContextCore*, origin : BLPoint*, path : BLPathCore*) : BLResult
    fun blContextFillPathDRgba32(self : BLContextCore*, origin : BLPoint*, path : BLPathCore*, rgba32 : UInt32) : BLResult
    fun blContextFillPathDRgba64(self : BLContextCore*, origin : BLPoint*, path : BLPathCore*, rgba64 : LibC::ULong) : BLResult
    fun blContextFillPathDExt(self : BLContextCore*, origin : BLPoint*, path : BLPathCore*, style : BLUnknown*) : BLResult
    fun blContextFillGeometry(self : BLContextCore*, type : BLGeometryType, data : Void*) : BLResult
    fun blContextFillGeometryRgba32(self : BLContextCore*, type : BLGeometryType, data : Void*, rgba32 : UInt32) : BLResult
    fun blContextFillGeometryRgba64(self : BLContextCore*, type : BLGeometryType, data : Void*, rgba64 : LibC::ULong) : BLResult
    fun blContextFillGeometryExt(self : BLContextCore*, type : BLGeometryType, data : Void*, style : BLUnknown*) : BLResult
    fun blContextFillUtf8TextI(self : BLContextCore*, origin : BLPointI*, font : BLFontCore*, text : UInt8*, size : LibC::ULong) : BLResult
    fun blContextFillUtf8TextIRgba32(self : BLContextCore*, origin : BLPointI*, font : BLFontCore*, text : UInt8*, size : LibC::ULong, rgba32 : UInt32) : BLResult
    fun blContextFillUtf8TextIRgba64(self : BLContextCore*, origin : BLPointI*, font : BLFontCore*, text : UInt8*, size : LibC::ULong, rgba64 : LibC::ULong) : BLResult
    fun blContextFillUtf8TextIExt(self : BLContextCore*, origin : BLPointI*, font : BLFontCore*, text : UInt8*, size : LibC::ULong, style : BLUnknown*) : BLResult
    fun blContextFillUtf8TextD(self : BLContextCore*, origin : BLPoint*, font : BLFontCore*, text : UInt8*, size : LibC::ULong) : BLResult
    fun blContextFillUtf8TextDRgba32(self : BLContextCore*, origin : BLPoint*, font : BLFontCore*, text : UInt8*, size : LibC::ULong, rgba32 : UInt32) : BLResult
    fun blContextFillUtf8TextDRgba64(self : BLContextCore*, origin : BLPoint*, font : BLFontCore*, text : UInt8*, size : LibC::ULong, rgba64 : LibC::ULong) : BLResult
    fun blContextFillUtf8TextDExt(self : BLContextCore*, origin : BLPoint*, font : BLFontCore*, text : UInt8*, size : LibC::ULong, style : BLUnknown*) : BLResult
    fun blContextFillUtf16TextI(self : BLContextCore*, origin : BLPointI*, font : BLFontCore*, text : UInt16*, size : LibC::ULong) : BLResult
    fun blContextFillUtf16TextIRgba32(self : BLContextCore*, origin : BLPointI*, font : BLFontCore*, text : UInt16*, size : LibC::ULong, rgba32 : UInt32) : BLResult
    fun blContextFillUtf16TextIRgba64(self : BLContextCore*, origin : BLPointI*, font : BLFontCore*, text : UInt16*, size : LibC::ULong, rgba64 : LibC::ULong) : BLResult
    fun blContextFillUtf16TextIExt(self : BLContextCore*, origin : BLPointI*, font : BLFontCore*, text : UInt16*, size : LibC::ULong, style : BLUnknown*) : BLResult
    fun blContextFillUtf16TextD(self : BLContextCore*, origin : BLPoint*, font : BLFontCore*, text : UInt16*, size : LibC::ULong) : BLResult
    fun blContextFillUtf16TextDRgba32(self : BLContextCore*, origin : BLPoint*, font : BLFontCore*, text : UInt16*, size : LibC::ULong, rgba32 : UInt32) : BLResult
    fun blContextFillUtf16TextDRgba64(self : BLContextCore*, origin : BLPoint*, font : BLFontCore*, text : UInt16*, size : LibC::ULong, rgba64 : LibC::ULong) : BLResult
    fun blContextFillUtf16TextDExt(self : BLContextCore*, origin : BLPoint*, font : BLFontCore*, text : UInt16*, size : LibC::ULong, style : BLUnknown*) : BLResult
    fun blContextFillUtf32TextI(self : BLContextCore*, origin : BLPointI*, font : BLFontCore*, text : UInt32*, size : LibC::ULong) : BLResult
    fun blContextFillUtf32TextIRgba32(self : BLContextCore*, origin : BLPointI*, font : BLFontCore*, text : UInt32*, size : LibC::ULong, rgba32 : UInt32) : BLResult
    fun blContextFillUtf32TextIRgba64(self : BLContextCore*, origin : BLPointI*, font : BLFontCore*, text : UInt32*, size : LibC::ULong, rgba64 : LibC::ULong) : BLResult
    fun blContextFillUtf32TextIExt(self : BLContextCore*, origin : BLPointI*, font : BLFontCore*, text : UInt32*, size : LibC::ULong, style : BLUnknown*) : BLResult
    fun blContextFillUtf32TextD(self : BLContextCore*, origin : BLPoint*, font : BLFontCore*, text : UInt32*, size : LibC::ULong) : BLResult
    fun blContextFillUtf32TextDRgba32(self : BLContextCore*, origin : BLPoint*, font : BLFontCore*, text : UInt32*, size : LibC::ULong, rgba32 : UInt32) : BLResult
    fun blContextFillUtf32TextDRgba64(self : BLContextCore*, origin : BLPoint*, font : BLFontCore*, text : UInt32*, size : LibC::ULong, rgba64 : LibC::ULong) : BLResult
    fun blContextFillUtf32TextDExt(self : BLContextCore*, origin : BLPoint*, font : BLFontCore*, text : UInt32*, size : LibC::ULong, style : BLUnknown*) : BLResult
    fun blContextFillGlyphRunI(self : BLContextCore*, origin : BLPointI*, font : BLFontCore*, glyph_run : BLGlyphRun*) : BLResult
    fun blContextFillGlyphRunIRgba32(self : BLContextCore*, origin : BLPointI*, font : BLFontCore*, glyph_run : BLGlyphRun*, rgba32 : UInt32) : BLResult
    fun blContextFillGlyphRunIRgba64(self : BLContextCore*, origin : BLPointI*, font : BLFontCore*, glyph_run : BLGlyphRun*, rgba64 : LibC::ULong) : BLResult
    fun blContextFillGlyphRunIExt(self : BLContextCore*, origin : BLPointI*, font : BLFontCore*, glyph_run : BLGlyphRun*, style : BLUnknown*) : BLResult
    fun blContextFillGlyphRunD(self : BLContextCore*, origin : BLPoint*, font : BLFontCore*, glyph_run : BLGlyphRun*) : BLResult
    fun blContextFillGlyphRunDRgba32(self : BLContextCore*, origin : BLPoint*, font : BLFontCore*, glyph_run : BLGlyphRun*, rgba32 : UInt32) : BLResult
    fun blContextFillGlyphRunDRgba64(self : BLContextCore*, origin : BLPoint*, font : BLFontCore*, glyph_run : BLGlyphRun*, rgba64 : LibC::ULong) : BLResult
    fun blContextFillGlyphRunDExt(self : BLContextCore*, origin : BLPoint*, font : BLFontCore*, glyph_run : BLGlyphRun*, style : BLUnknown*) : BLResult
    fun blContextFillMaskI(self : BLContextCore*, origin : BLPointI*, mask : BLImageCore*, mask_area : BLRectI*) : BLResult
    fun blContextFillMaskIRgba32(self : BLContextCore*, origin : BLPointI*, mask : BLImageCore*, mask_area : BLRectI*, rgba32 : UInt32) : BLResult
    fun blContextFillMaskIRgba64(self : BLContextCore*, origin : BLPointI*, mask : BLImageCore*, mask_area : BLRectI*, rgba64 : LibC::ULong) : BLResult
    fun blContextFillMaskIExt(self : BLContextCore*, origin : BLPointI*, mask : BLImageCore*, mask_area : BLRectI*, style : BLUnknown*) : BLResult
    fun blContextFillMaskD(self : BLContextCore*, origin : BLPoint*, mask : BLImageCore*, mask_area : BLRectI*) : BLResult
    fun blContextFillMaskDRgba32(self : BLContextCore*, origin : BLPoint*, mask : BLImageCore*, mask_area : BLRectI*, rgba32 : UInt32) : BLResult
    fun blContextFillMaskDRgba64(self : BLContextCore*, origin : BLPoint*, mask : BLImageCore*, mask_area : BLRectI*, rgba64 : LibC::ULong) : BLResult
    fun blContextFillMaskDExt(self : BLContextCore*, origin : BLPoint*, mask : BLImageCore*, mask_area : BLRectI*, style : BLUnknown*) : BLResult
    fun blContextStrokeRectI(self : BLContextCore*, rect : BLRectI*) : BLResult
    fun blContextStrokeRectIRgba32(self : BLContextCore*, rect : BLRectI*, rgba32 : UInt32) : BLResult
    fun blContextStrokeRectIRgba64(self : BLContextCore*, rect : BLRectI*, rgba64 : LibC::ULong) : BLResult
    fun blContextStrokeRectIExt(self : BLContextCore*, rect : BLRectI*, style : BLUnknown*) : BLResult
    fun blContextStrokeRectD(self : BLContextCore*, rect : BLRect*) : BLResult
    fun blContextStrokeRectDRgba32(self : BLContextCore*, rect : BLRect*, rgba32 : UInt32) : BLResult
    fun blContextStrokeRectDRgba64(self : BLContextCore*, rect : BLRect*, rgba64 : LibC::ULong) : BLResult
    fun blContextStrokeRectDExt(self : BLContextCore*, rect : BLRect*, style : BLUnknown*) : BLResult
    fun blContextStrokePathD(self : BLContextCore*, origin : BLPoint*, path : BLPathCore*) : BLResult
    fun blContextStrokePathDRgba32(self : BLContextCore*, origin : BLPoint*, path : BLPathCore*, rgba32 : UInt32) : BLResult
    fun blContextStrokePathDRgba64(self : BLContextCore*, origin : BLPoint*, path : BLPathCore*, rgba64 : LibC::ULong) : BLResult
    fun blContextStrokePathDExt(self : BLContextCore*, origin : BLPoint*, path : BLPathCore*, style : BLUnknown*) : BLResult
    fun blContextStrokeGeometry(self : BLContextCore*, type : BLGeometryType, data : Void*) : BLResult
    fun blContextStrokeGeometryRgba32(self : BLContextCore*, type : BLGeometryType, data : Void*, rgba32 : UInt32) : BLResult
    fun blContextStrokeGeometryRgba64(self : BLContextCore*, type : BLGeometryType, data : Void*, rgba64 : LibC::ULong) : BLResult
    fun blContextStrokeGeometryExt(self : BLContextCore*, type : BLGeometryType, data : Void*, style : BLUnknown*) : BLResult
    fun blContextStrokeUtf8TextI(self : BLContextCore*, origin : BLPointI*, font : BLFontCore*, text : UInt8*, size : LibC::ULong) : BLResult
    fun blContextStrokeUtf8TextIRgba32(self : BLContextCore*, origin : BLPointI*, font : BLFontCore*, text : UInt8*, size : LibC::ULong, rgba32 : UInt32) : BLResult
    fun blContextStrokeUtf8TextIRgba64(self : BLContextCore*, origin : BLPointI*, font : BLFontCore*, text : UInt8*, size : LibC::ULong, rgba64 : LibC::ULong) : BLResult
    fun blContextStrokeUtf8TextIExt(self : BLContextCore*, origin : BLPointI*, font : BLFontCore*, text : UInt8*, size : LibC::ULong, style : BLUnknown*) : BLResult
    fun blContextStrokeUtf8TextD(self : BLContextCore*, origin : BLPoint*, font : BLFontCore*, text : UInt8*, size : LibC::ULong) : BLResult
    fun blContextStrokeUtf8TextDRgba32(self : BLContextCore*, origin : BLPoint*, font : BLFontCore*, text : UInt8*, size : LibC::ULong, rgba32 : UInt32) : BLResult
    fun blContextStrokeUtf8TextDRgba64(self : BLContextCore*, origin : BLPoint*, font : BLFontCore*, text : UInt8*, size : LibC::ULong, rgba64 : LibC::ULong) : BLResult
    fun blContextStrokeUtf8TextDExt(self : BLContextCore*, origin : BLPoint*, font : BLFontCore*, text : UInt8*, size : LibC::ULong, style : BLUnknown*) : BLResult
    fun blContextStrokeUtf16TextI(self : BLContextCore*, origin : BLPointI*, font : BLFontCore*, text : UInt16*, size : LibC::ULong) : BLResult
    fun blContextStrokeUtf16TextIRgba32(self : BLContextCore*, origin : BLPointI*, font : BLFontCore*, text : UInt16*, size : LibC::ULong, rgba32 : UInt32) : BLResult
    fun blContextStrokeUtf16TextIRgba64(self : BLContextCore*, origin : BLPointI*, font : BLFontCore*, text : UInt16*, size : LibC::ULong, rgba64 : LibC::ULong) : BLResult
    fun blContextStrokeUtf16TextIExt(self : BLContextCore*, origin : BLPointI*, font : BLFontCore*, text : UInt16*, size : LibC::ULong, style : BLUnknown*) : BLResult
    fun blContextStrokeUtf16TextD(self : BLContextCore*, origin : BLPoint*, font : BLFontCore*, text : UInt16*, size : LibC::ULong) : BLResult
    fun blContextStrokeUtf16TextDRgba32(self : BLContextCore*, origin : BLPoint*, font : BLFontCore*, text : UInt16*, size : LibC::ULong, rgba32 : UInt32) : BLResult
    fun blContextStrokeUtf16TextDRgba64(self : BLContextCore*, origin : BLPoint*, font : BLFontCore*, text : UInt16*, size : LibC::ULong, rgba64 : LibC::ULong) : BLResult
    fun blContextStrokeUtf16TextDExt(self : BLContextCore*, origin : BLPoint*, font : BLFontCore*, text : UInt16*, size : LibC::ULong, style : BLUnknown*) : BLResult
    fun blContextStrokeUtf32TextI(self : BLContextCore*, origin : BLPointI*, font : BLFontCore*, text : UInt32*, size : LibC::ULong) : BLResult
    fun blContextStrokeUtf32TextIRgba32(self : BLContextCore*, origin : BLPointI*, font : BLFontCore*, text : UInt32*, size : LibC::ULong, rgba32 : UInt32) : BLResult
    fun blContextStrokeUtf32TextIRgba64(self : BLContextCore*, origin : BLPointI*, font : BLFontCore*, text : UInt32*, size : LibC::ULong, rgba64 : LibC::ULong) : BLResult
    fun blContextStrokeUtf32TextIExt(self : BLContextCore*, origin : BLPointI*, font : BLFontCore*, text : UInt32*, size : LibC::ULong, style : BLUnknown*) : BLResult
    fun blContextStrokeUtf32TextD(self : BLContextCore*, origin : BLPoint*, font : BLFontCore*, text : UInt32*, size : LibC::ULong) : BLResult
    fun blContextStrokeUtf32TextDRgba32(self : BLContextCore*, origin : BLPoint*, font : BLFontCore*, text : UInt32*, size : LibC::ULong, rgba32 : UInt32) : BLResult
    fun blContextStrokeUtf32TextDRgba64(self : BLContextCore*, origin : BLPoint*, font : BLFontCore*, text : UInt32*, size : LibC::ULong, rgba64 : LibC::ULong) : BLResult
    fun blContextStrokeUtf32TextDExt(self : BLContextCore*, origin : BLPoint*, font : BLFontCore*, text : UInt32*, size : LibC::ULong, style : BLUnknown*) : BLResult
    fun blContextStrokeGlyphRunI(self : BLContextCore*, origin : BLPointI*, font : BLFontCore*, glyph_run : BLGlyphRun*) : BLResult
    fun blContextStrokeGlyphRunIRgba32(self : BLContextCore*, origin : BLPointI*, font : BLFontCore*, glyph_run : BLGlyphRun*, rgba32 : UInt32) : BLResult
    fun blContextStrokeGlyphRunIRgba64(self : BLContextCore*, origin : BLPointI*, font : BLFontCore*, glyph_run : BLGlyphRun*, rgba64 : LibC::ULong) : BLResult
    fun blContextStrokeGlyphRunIExt(self : BLContextCore*, origin : BLPointI*, font : BLFontCore*, glyph_run : BLGlyphRun*, style : BLUnknown*) : BLResult
    fun blContextStrokeGlyphRunD(self : BLContextCore*, origin : BLPoint*, font : BLFontCore*, glyph_run : BLGlyphRun*) : BLResult
    fun blContextStrokeGlyphRunDRgba32(self : BLContextCore*, origin : BLPoint*, font : BLFontCore*, glyph_run : BLGlyphRun*, rgba32 : UInt32) : BLResult
    fun blContextStrokeGlyphRunDRgba64(self : BLContextCore*, origin : BLPoint*, font : BLFontCore*, glyph_run : BLGlyphRun*, rgba64 : LibC::ULong) : BLResult
    fun blContextStrokeGlyphRunDExt(self : BLContextCore*, origin : BLPoint*, font : BLFontCore*, glyph_run : BLGlyphRun*, style : BLUnknown*) : BLResult
    fun blContextBlitImageI(self : BLContextCore*, origin : BLPointI*, img : BLImageCore*, img_area : BLRectI*) : BLResult
    fun blContextBlitImageD(self : BLContextCore*, origin : BLPoint*, img : BLImageCore*, img_area : BLRectI*) : BLResult
    fun blContextBlitScaledImageI(self : BLContextCore*, rect : BLRectI*, img : BLImageCore*, img_area : BLRectI*) : BLResult
    fun blContextBlitScaledImageD(self : BLContextCore*, rect : BLRect*, img : BLImageCore*, img_area : BLRectI*) : BLResult

    enum BLContextType : UInt32
      None   = 0
      Dummy  = 1
      Raster = 3
    end

    enum BLContextHint : UInt32
      RenderingQuality = 0
      GradientQuality  = 1
      PatternQuality   = 2
    end

    enum BLContextStyleSlot : UInt32
      Fill   = 0
      Stroke = 1
    end

    enum BLContextRenderTextOp : UInt32
      UTF8     = 0
      UTF16    = 1
      UTF32    = 2
      Latin1   = 3
      Wchar    = 2
      GlyphRun = 4
    end

    enum BLContextFlushFlags : UInt32
      NoFlags =          0
      Sync    = 2147483648
    end

    enum BLContextCreateFlags : UInt32
      NoFlags             =         0
      DisableJit          =         1
      FallbackToSync      =   1048576
      IsolatedThreadPool  =  16777216
      IsolatedJitRuntime  =  33554432
      IsolatedJitLogging  =  67108864
      OverrideCpuFeatures = 134217728
    end

    enum BLContextErrorFlags : UInt32
      NoFlags             =          0
      InvalidValue        =          1
      InvalidState        =          2
      InvalidGeometry     =          4
      InvalidGlyph        =          8
      InvalidFont         =         16
      ThreadPoolExhausted =  536870912
      OutOfMemory         = 1073741824
      UnknownError        = 2147483648
    end

    enum BLContextStyleSwapMode : UInt32
      Styles          = 0
      StylesWithAlpha = 1
    end

    enum BLContextStyleTransformMode : UInt32
      User = 0
      Meta = 1
      None = 2
    end

    enum BLClipMode : UInt32
      AlignedRect   = 0
      UnalignedRect = 1
      Mask          = 2
      Count         = 3
    end

    enum BLCompOp : UInt32
      SrcOver     =  0
      SrcCopy     =  1
      SrcIn       =  2
      SrcOut      =  3
      SrcAtop     =  4
      DstOver     =  5
      DstCopy     =  6
      DstIn       =  7
      DstOut      =  8
      DstAtop     =  9
      Xor         = 10
      Clear       = 11
      Plus        = 12
      Minus       = 13
      Modulate    = 14
      Multiply    = 15
      Screen      = 16
      Overlay     = 17
      Darken      = 18
      Lighten     = 19
      ColorDodge  = 20
      ColorBurn   = 21
      LinearBurn  = 22
      LinearLight = 23
      PinLight    = 24
      HardLight   = 25
      SoftLight   = 26
      Difference  = 27
      Exclusion   = 28
    end

    enum BLRenderingQuality : UInt32
      Antialias = 0
    end

    struct BLContextCreateInfo
      flags : UInt32
      thread_count : UInt32
      cpu_features : UInt32
      command_queue_limit : UInt32
      saved_state_limit : UInt32
      pixel_origin : BLPointI
      reserved : UInt32[1]
    end

    struct BLContextCookie
      data : LibC::ULong[2]
    end

    struct BLContextHints
      hints : UInt8[8]
    end

    struct BLContextCore
      _d : BLContextImpl*
    end

    struct BLContextState
      target_image : BLImageCore*
      target_size : BLSize
      hints : BLContextHints
      comp_op : UInt8
      fill_rule : UInt8
      style_type : UInt8[2]
      saved_state_count : UInt32
      global_alpha : Float64
      style_alpha : Float64[2]
      stroke_options : BLStrokeOptionsCore
      approximation_options : BLApproximationOptions
      meta_transform : BLMatrix2D
      user_transform : BLMatrix2D
      final_transform : BLMatrix2D
    end

    struct BLContextVirt
      base : BLObjectVirtBase
      apply_transform_op : (BLContextImpl*, BLTransformOp, Void*) -> BLResult*
      fill_rect_i : (BLContextImpl*, BLRectI*) -> BLResult*
      fill_rect_i_rgba32 : (BLContextImpl*, BLRectI*, UInt32) -> BLResult*
      fill_rect_i_ext : (BLContextImpl*, BLRectI*, BLObjectCore*) -> BLResult*
      fill_rect_d : (BLContextImpl*, BLRect*) -> BLResult*
      fill_rect_d_rgba32 : (BLContextImpl*, BLRect*, UInt32) -> BLResult*
      fill_rect_d_ext : (BLContextImpl*, BLRect*, BLObjectCore*) -> BLResult*
      fill_path_d : (BLContextImpl*, BLPoint*, BLPathCore*) -> BLResult*
      fill_path_d_rgba32 : (BLContextImpl*, BLPoint*, BLPathCore*, UInt32) -> BLResult*
      fill_path_d_ext : (BLContextImpl*, BLPoint*, BLPathCore*, BLObjectCore*) -> BLResult*
      blit_image_i : (BLContextImpl*, BLPointI*, BLImageCore*, BLRectI*) -> BLResult*
      blit_scaled_image_i : (BLContextImpl*, BLRectI*, BLImageCore*, BLRectI*) -> BLResult*
      flush : (BLContextImpl*, BLContextFlushFlags) -> BLResult*
      save : (BLContextImpl*, BLContextCookie*) -> BLResult*
      restore : (BLContextImpl*, BLContextCookie*) -> BLResult*
      user_to_meta : (BLContextImpl*) -> BLResult*
      set_hint : (BLContextImpl*, BLContextHint, UInt32) -> BLResult*
      set_hints : (BLContextImpl*, BLContextHints*) -> BLResult*
      set_flatten_mode : (BLContextImpl*, BLFlattenMode) -> BLResult*
      set_flatten_tolerance : (BLContextImpl*, Float64) -> BLResult*
      set_approximation_options : (BLContextImpl*, BLApproximationOptions*) -> BLResult*
      get_style : (BLContextImpl*, BLContextStyleSlot, Bool, BLVarCore*) -> BLResult*
      set_style : (BLContextImpl*, BLContextStyleSlot, BLObjectCore*, BLContextStyleTransformMode) -> BLResult*
      set_style_rgba : (BLContextImpl*, BLContextStyleSlot, BLRgba*) -> BLResult*
      set_style_rgba32 : (BLContextImpl*, BLContextStyleSlot, UInt32) -> BLResult*
      set_style_rgba64 : (BLContextImpl*, BLContextStyleSlot, LibC::ULong) -> BLResult*
      disable_style : (BLContextImpl*, BLContextStyleSlot) -> BLResult*
      set_style_alpha : (BLContextImpl*, BLContextStyleSlot, Float64) -> BLResult*
      swap_styles : (BLContextImpl*, BLContextStyleSwapMode) -> BLResult*
      set_global_alpha : (BLContextImpl*, Float64) -> BLResult*
      set_comp_op : (BLContextImpl*, BLCompOp) -> BLResult*
      set_fill_rule : (BLContextImpl*, BLFillRule) -> BLResult*
      set_stroke_width : (BLContextImpl*, Float64) -> BLResult*
      set_stroke_miter_limit : (BLContextImpl*, Float64) -> BLResult*
      set_stroke_cap : (BLContextImpl*, BLStrokeCapPosition, BLStrokeCap) -> BLResult*
      set_stroke_caps : (BLContextImpl*, BLStrokeCap) -> BLResult*
      set_stroke_join : (BLContextImpl*, BLStrokeJoin) -> BLResult*
      set_stroke_dash_offset : (BLContextImpl*, Float64) -> BLResult*
      set_stroke_dash_array : (BLContextImpl*, BLArrayCore*) -> BLResult*
      set_stroke_transform_order : (BLContextImpl*, BLStrokeTransformOrder) -> BLResult*
      set_stroke_options : (BLContextImpl*, BLStrokeOptionsCore*) -> BLResult*
      clip_to_rect_i : (BLContextImpl*, BLRectI*) -> BLResult*
      clip_to_rect_d : (BLContextImpl*, BLRect*) -> BLResult*
      restore_clipping : (BLContextImpl*) -> BLResult*
      clear_all : (BLContextImpl*) -> BLResult*
      clear_rect_i : (BLContextImpl*, BLRectI*) -> BLResult*
      clear_rect_d : (BLContextImpl*, BLRect*) -> BLResult*
      fill_all : (BLContextImpl*) -> BLResult*
      fill_all_rgba32 : (BLContextImpl*, UInt32) -> BLResult*
      fill_all_ext : (BLContextImpl*, BLObjectCore*) -> BLResult*
      fill_geometry : (BLContextImpl*, BLGeometryType, Void*) -> BLResult*
      fill_geometry_rgba32 : (BLContextImpl*, BLGeometryType, Void*, UInt32) -> BLResult*
      fill_geometry_ext : (BLContextImpl*, BLGeometryType, Void*, BLObjectCore*) -> BLResult*
      fill_text_op_i : (BLContextImpl*, BLPointI*, BLFontCore*, BLContextRenderTextOp, Void*) -> BLResult*
      fill_text_op_i_rgba32 : (BLContextImpl*, BLPointI*, BLFontCore*, BLContextRenderTextOp, Void*, UInt32) -> BLResult*
      fill_text_op_i_ext : (BLContextImpl*, BLPointI*, BLFontCore*, BLContextRenderTextOp, Void*, BLObjectCore*) -> BLResult*
      fill_text_op_d : (BLContextImpl*, BLPoint*, BLFontCore*, BLContextRenderTextOp, Void*) -> BLResult*
      fill_text_op_d_rgba32 : (BLContextImpl*, BLPoint*, BLFontCore*, BLContextRenderTextOp, Void*, UInt32) -> BLResult*
      fill_text_op_d_ext : (BLContextImpl*, BLPoint*, BLFontCore*, BLContextRenderTextOp, Void*, BLObjectCore*) -> BLResult*
      fill_mask_i : (BLContextImpl*, BLPointI*, BLImageCore*, BLRectI*) -> BLResult*
      fill_mask_i_rgba32 : (BLContextImpl*, BLPointI*, BLImageCore*, BLRectI*, UInt32) -> BLResult*
      fill_mask_i_ext : (BLContextImpl*, BLPointI*, BLImageCore*, BLRectI*, BLObjectCore*) -> BLResult*
      fill_mask_d : (BLContextImpl*, BLPoint*, BLImageCore*, BLRectI*) -> BLResult*
      fill_mask_d_rgba32 : (BLContextImpl*, BLPoint*, BLImageCore*, BLRectI*, UInt32) -> BLResult*
      fill_mask_d_ext : (BLContextImpl*, BLPoint*, BLImageCore*, BLRectI*, BLObjectCore*) -> BLResult*
      stroke_path_d : (BLContextImpl*, BLPoint*, BLPathCore*) -> BLResult*
      stroke_path_d_rgba32 : (BLContextImpl*, BLPoint*, BLPathCore*, UInt32) -> BLResult*
      stroke_path_d_ext : (BLContextImpl*, BLPoint*, BLPathCore*, BLObjectCore*) -> BLResult*
      stroke_geometry : (BLContextImpl*, BLGeometryType, Void*) -> BLResult*
      stroke_geometry_rgba32 : (BLContextImpl*, BLGeometryType, Void*, UInt32) -> BLResult*
      stroke_geometry_ext : (BLContextImpl*, BLGeometryType, Void*, BLObjectCore*) -> BLResult*
      stroke_text_op_i : (BLContextImpl*, BLPointI*, BLFontCore*, BLContextRenderTextOp, Void*) -> BLResult*
      stroke_text_op_i_rgba32 : (BLContextImpl*, BLPointI*, BLFontCore*, BLContextRenderTextOp, Void*, UInt32) -> BLResult*
      stroke_text_op_i_ext : (BLContextImpl*, BLPointI*, BLFontCore*, BLContextRenderTextOp, Void*, BLObjectCore*) -> BLResult*
      stroke_text_op_d : (BLContextImpl*, BLPoint*, BLFontCore*, BLContextRenderTextOp, Void*) -> BLResult*
      stroke_text_op_d_rgba32 : (BLContextImpl*, BLPoint*, BLFontCore*, BLContextRenderTextOp, Void*, UInt32) -> BLResult*
      stroke_text_op_d_ext : (BLContextImpl*, BLPoint*, BLFontCore*, BLContextRenderTextOp, Void*, BLObjectCore*) -> BLResult*
      blit_image_d : (BLContextImpl*, BLPoint*, BLImageCore*, BLRectI*) -> BLResult*
      blit_scaled_image_d : (BLContextImpl*, BLRect*, BLImageCore*, BLRectI*) -> BLResult*
    end

    struct BLContextImpl
      virt : BLContextVirt*
      state : BLContextState*
      context_type : UInt32
    end
  end
end
