# This file is automatically generated and should not be manually edited

module Blend2D
  @[Link("blend2d")]
  lib LibBlend2D
    fun blFontDataInit(self : BLFontDataCore*) : BLResult
    fun blFontDataInitMove(self : BLFontDataCore*, other : BLFontDataCore*) : BLResult
    fun blFontDataInitWeak(self : BLFontDataCore*, other : BLFontDataCore*) : BLResult
    fun blFontDataDestroy(self : BLFontDataCore*) : BLResult
    fun blFontDataReset(self : BLFontDataCore*) : BLResult
    fun blFontDataAssignMove(self : BLFontDataCore*, other : BLFontDataCore*) : BLResult
    fun blFontDataAssignWeak(self : BLFontDataCore*, other : BLFontDataCore*) : BLResult
    fun blFontDataCreateFromFile(self : BLFontDataCore*, file_name : UInt8*, read_flags : BLFileReadFlags) : BLResult
    fun blFontDataCreateFromDataArray(self : BLFontDataCore*, data_array : BLArrayCore*) : BLResult
    fun blFontDataCreateFromData(self : BLFontDataCore*, data : Void*, data_size : Int32, destroy_func : BLDestroyExternalDataFunc, user_data : Void*) : BLResult
    fun blFontDataEquals(a : BLFontDataCore*, b : BLFontDataCore*) : Int32
    fun blFontDataGetFaceCount(self : BLFontDataCore*) : UInt32
    fun blFontDataGetFaceType(self : BLFontDataCore*) : BLFontFaceType
    fun blFontDataGetFlags(self : BLFontDataCore*) : BLFontDataFlags
    fun blFontDataGetTableTags(self : BLFontDataCore*, face_index : UInt32, dst : BLArrayCore*) : BLResult
    fun blFontDataGetTables(self : BLFontDataCore*, face_index : UInt32, dst : BLFontTable*, tags : BLTag*, count : Int32) : Int32

    enum BLFontDataFlags : UInt32
      NoFlags    = 0
      Collection = 1
    end

    struct BLFontTable
      data : UInt8*
      size : Int32
    end

    struct BLFontDataCore
      _d : BLFontDataImpl*
    end

    struct BLFontDataVirt
      base : BLObjectVirtBase
      get_table_tags : (BLFontDataImpl*, UInt32, BLArrayCore*) -> BLResult*
      size_t : (Int32*) -> (BLFontDataImpl*, UInt32, BLFontTable*, BLTag*, Int32) -> Int32
    end

    struct BLFontDataImpl
      virt : BLFontDataVirt*
      face_type : UInt8
      face_count : UInt32
      flags : UInt32
    end
  end
end
