# This file is automatically generated and should not be manually edited

module Blend2D
  @[Link("blend2d")]
  lib LibBlend2D
    fun blFontVariationSettingsInit(self : BLFontVariationSettingsCore*) : BLResult
    fun blFontVariationSettingsInitMove(self : BLFontVariationSettingsCore*, other : BLFontVariationSettingsCore*) : BLResult
    fun blFontVariationSettingsInitWeak(self : BLFontVariationSettingsCore*, other : BLFontVariationSettingsCore*) : BLResult
    fun blFontVariationSettingsDestroy(self : BLFontVariationSettingsCore*) : BLResult
    fun blFontVariationSettingsReset(self : BLFontVariationSettingsCore*) : BLResult
    fun blFontVariationSettingsClear(self : BLFontVariationSettingsCore*) : BLResult
    fun blFontVariationSettingsShrink(self : BLFontVariationSettingsCore*) : BLResult
    fun blFontVariationSettingsAssignMove(self : BLFontVariationSettingsCore*, other : BLFontVariationSettingsCore*) : BLResult
    fun blFontVariationSettingsAssignWeak(self : BLFontVariationSettingsCore*, other : BLFontVariationSettingsCore*) : BLResult
    fun blFontVariationSettingsGetSize(self : BLFontVariationSettingsCore*) : Int32
    fun blFontVariationSettingsGetCapacity(self : BLFontVariationSettingsCore*) : Int32
    fun blFontVariationSettingsGetView(self : BLFontVariationSettingsCore*, out : BLFontVariationSettingsView*) : BLResult
    fun blFontVariationSettingsHasValue(self : BLFontVariationSettingsCore*, variation_tag : BLTag) : Int32
    fun blFontVariationSettingsGetValue(self : BLFontVariationSettingsCore*, variation_tag : BLTag) : Float32
    fun blFontVariationSettingsSetValue(self : BLFontVariationSettingsCore*, variation_tag : BLTag, value : Float32) : BLResult
    fun blFontVariationSettingsRemoveValue(self : BLFontVariationSettingsCore*, variation_tag : BLTag) : BLResult
    fun blFontVariationSettingsEquals(a : BLFontVariationSettingsCore*, b : BLFontVariationSettingsCore*) : Int32

    struct BLFontVariationItem
      tag : BLTag
      value : Float32
    end

    struct BLFontVariationSettingsView
      data : BLFontVariationItem*
      size : Int32
      sso_data : BLFontVariationItem[3]
    end

    struct BLFontVariationSettingsCore
      _d : BLFontVariationSettingsImpl*
    end

    struct BLFontVariationSettingsImpl
      data : BLFontVariationItem*
      size : Int32
      capacity : Int32
    end
  end
end
