# This file is automatically generated and should not be manually edited

module Blend2D
  @[Link("blend2d")]
  lib LibBlend2D
    fun blFontFeatureSettingsInit(self : BLFontFeatureSettingsCore*) : BLResult
    fun blFontFeatureSettingsInitMove(self : BLFontFeatureSettingsCore*, other : BLFontFeatureSettingsCore*) : BLResult
    fun blFontFeatureSettingsInitWeak(self : BLFontFeatureSettingsCore*, other : BLFontFeatureSettingsCore*) : BLResult
    fun blFontFeatureSettingsDestroy(self : BLFontFeatureSettingsCore*) : BLResult
    fun blFontFeatureSettingsReset(self : BLFontFeatureSettingsCore*) : BLResult
    fun blFontFeatureSettingsClear(self : BLFontFeatureSettingsCore*) : BLResult
    fun blFontFeatureSettingsShrink(self : BLFontFeatureSettingsCore*) : BLResult
    fun blFontFeatureSettingsAssignMove(self : BLFontFeatureSettingsCore*, other : BLFontFeatureSettingsCore*) : BLResult
    fun blFontFeatureSettingsAssignWeak(self : BLFontFeatureSettingsCore*, other : BLFontFeatureSettingsCore*) : BLResult
    fun blFontFeatureSettingsGetSize(self : BLFontFeatureSettingsCore*) : LibC::ULong
    fun blFontFeatureSettingsGetCapacity(self : BLFontFeatureSettingsCore*) : LibC::ULong
    fun blFontFeatureSettingsGetView(self : BLFontFeatureSettingsCore*, out : BLFontFeatureSettingsView*) : BLResult
    fun blFontFeatureSettingsHasValue(self : BLFontFeatureSettingsCore*, feature_tag : BLTag) : Bool
    fun blFontFeatureSettingsGetValue(self : BLFontFeatureSettingsCore*, feature_tag : BLTag) : UInt32
    fun blFontFeatureSettingsSetValue(self : BLFontFeatureSettingsCore*, feature_tag : BLTag, value : UInt32) : BLResult
    fun blFontFeatureSettingsRemoveValue(self : BLFontFeatureSettingsCore*, feature_tag : BLTag) : BLResult
    fun blFontFeatureSettingsEquals(a : BLFontFeatureSettingsCore*, b : BLFontFeatureSettingsCore*) : Bool

    struct BLFontFeatureItem
      tag : BLTag
      value : UInt32
    end

    struct BLFontFeatureSettingsView
      data : BLFontFeatureItem*
      size : LibC::ULong
      sso_data : BLFontFeatureItem[36]
    end

    struct BLFontFeatureSettingsCore
      _d : BLFontFeatureSettingsImpl*
    end

    struct BLFontFeatureSettingsImpl
      data : BLFontFeatureItem*
      size : LibC::ULong
      capacity : LibC::ULong
    end
  end
end
