# This file is automatically generated and should not be manually edited

module Blend2D
  @[Link("blend2d")]
  lib LibBlend2D
    fun blFontInit(self : BLFontCore*) : BLResult
    fun blFontInitMove(self : BLFontCore*, other : BLFontCore*) : BLResult
    fun blFontInitWeak(self : BLFontCore*, other : BLFontCore*) : BLResult
    fun blFontDestroy(self : BLFontCore*) : BLResult
    fun blFontReset(self : BLFontCore*) : BLResult
    fun blFontAssignMove(self : BLFontCore*, other : BLFontCore*) : BLResult
    fun blFontAssignWeak(self : BLFontCore*, other : BLFontCore*) : BLResult
    fun blFontEquals(a : BLFontCore*, b : BLFontCore*) : Int32
    fun blFontCreateFromFace(self : BLFontCore*, face : BLFontFaceCore*, size : Float32) : BLResult
    fun blFontCreateFromFaceWithSettings(self : BLFontCore*, face : BLFontFaceCore*, size : Float32, feature_settings : BLFontFeatureSettingsCore*, variation_settings : BLFontVariationSettingsCore*) : BLResult
    fun blFontGetFace(self : BLFontCore*, out : BLFontFaceCore*) : BLResult
    fun blFontGetSize(self : BLFontCore*) : Float32
    fun blFontSetSize(self : BLFontCore*, size : Float32) : BLResult
    fun blFontGetMetrics(self : BLFontCore*, out : BLFontMetrics*) : BLResult
    fun blFontGetMatrix(self : BLFontCore*, out : BLFontMatrix*) : BLResult
    fun blFontGetDesignMetrics(self : BLFontCore*, out : BLFontDesignMetrics*) : BLResult
    fun blFontGetFeatureSettings(self : BLFontCore*, out : BLFontFeatureSettingsCore*) : BLResult
    fun blFontSetFeatureSettings(self : BLFontCore*, feature_settings : BLFontFeatureSettingsCore*) : BLResult
    fun blFontResetFeatureSettings(self : BLFontCore*) : BLResult
    fun blFontGetVariationSettings(self : BLFontCore*, out : BLFontVariationSettingsCore*) : BLResult
    fun blFontSetVariationSettings(self : BLFontCore*, variation_settings : BLFontVariationSettingsCore*) : BLResult
    fun blFontResetVariationSettings(self : BLFontCore*) : BLResult
    fun blFontShape(self : BLFontCore*, gb : BLGlyphBufferCore*) : BLResult
    fun blFontMapTextToGlyphs(self : BLFontCore*, gb : BLGlyphBufferCore*, state_out : BLGlyphMappingState*) : BLResult
    fun blFontPositionGlyphs(self : BLFontCore*, gb : BLGlyphBufferCore*) : BLResult
    fun blFontApplyKerning(self : BLFontCore*, gb : BLGlyphBufferCore*) : BLResult
    fun blFontApplyGSub(self : BLFontCore*, gb : BLGlyphBufferCore*, lookups : BLBitArrayCore*) : BLResult
    fun blFontApplyGPos(self : BLFontCore*, gb : BLGlyphBufferCore*, lookups : BLBitArrayCore*) : BLResult
    fun blFontGetTextMetrics(self : BLFontCore*, gb : BLGlyphBufferCore*, out : BLTextMetrics*) : BLResult
    fun blFontGetGlyphBounds(self : BLFontCore*, glyph_data : UInt32*, glyph_advance : LibC::Long, out : BLBoxI*, count : Int32) : BLResult
    fun blFontGetGlyphAdvances(self : BLFontCore*, glyph_data : UInt32*, glyph_advance : LibC::Long, out : BLGlyphPlacement*, count : Int32) : BLResult
    fun blFontGetGlyphOutlines(self : BLFontCore*, glyph_id : BLGlyphId, user_transform : BLMatrix2D*, out : BLPathCore*, sink : BLPathSinkFunc, user_data : Void*) : BLResult
    fun blFontGetGlyphRunOutlines(self : BLFontCore*, glyph_run : BLGlyphRun*, user_transform : BLMatrix2D*, out : BLPathCore*, sink : BLPathSinkFunc, user_data : Void*) : BLResult

    struct BLFontCore
      _d : BLFontImpl*
    end

    struct BLFontImpl
      face : BLFontFaceCore
      weight : UInt16
      stretch : UInt8
      style : UInt8
      reserved : UInt32
      metrics : BLFontMetrics
      matrix : BLFontMatrix
      feature_settings : BLFontFeatureSettingsCore
      variation_settings : BLFontVariationSettingsCore
    end
  end
end
