# This file is automatically generated and should not be manually edited

module Blend2D
  @[Link("blend2d")]
  lib LibBlend2D
    fun blFontFaceInit(self : BLFontFaceCore*) : BLResult
    fun blFontFaceInitMove(self : BLFontFaceCore*, other : BLFontFaceCore*) : BLResult
    fun blFontFaceInitWeak(self : BLFontFaceCore*, other : BLFontFaceCore*) : BLResult
    fun blFontFaceDestroy(self : BLFontFaceCore*) : BLResult
    fun blFontFaceReset(self : BLFontFaceCore*) : BLResult
    fun blFontFaceAssignMove(self : BLFontFaceCore*, other : BLFontFaceCore*) : BLResult
    fun blFontFaceAssignWeak(self : BLFontFaceCore*, other : BLFontFaceCore*) : BLResult
    fun blFontFaceEquals(a : BLFontFaceCore*, b : BLFontFaceCore*) : Bool
    fun blFontFaceCreateFromFile(self : BLFontFaceCore*, file_name : UInt8*, read_flags : BLFileReadFlags) : BLResult
    fun blFontFaceCreateFromData(self : BLFontFaceCore*, font_data : BLFontDataCore*, face_index : UInt32) : BLResult
    fun blFontFaceGetFullName(self : BLFontFaceCore*, out : BLStringCore*) : BLResult
    fun blFontFaceGetFamilyName(self : BLFontFaceCore*, out : BLStringCore*) : BLResult
    fun blFontFaceGetSubfamilyName(self : BLFontFaceCore*, out : BLStringCore*) : BLResult
    fun blFontFaceGetPostScriptName(self : BLFontFaceCore*, out : BLStringCore*) : BLResult
    fun blFontFaceGetFaceInfo(self : BLFontFaceCore*, out : BLFontFaceInfo*) : BLResult
    fun blFontFaceGetDesignMetrics(self : BLFontFaceCore*, out : BLFontDesignMetrics*) : BLResult
    fun blFontFaceGetUnicodeCoverage(self : BLFontFaceCore*, out : BLFontUnicodeCoverage*) : BLResult
    fun blFontFaceGetCharacterCoverage(self : BLFontFaceCore*, out : BLBitSetCore*) : BLResult
    fun blFontFaceHasScriptTag(self : BLFontFaceCore*, script_tag : BLTag) : Bool
    fun blFontFaceHasFeatureTag(self : BLFontFaceCore*, feature_tag : BLTag) : Bool
    fun blFontFaceHasVariationTag(self : BLFontFaceCore*, variation_tag : BLTag) : Bool
    fun blFontFaceGetScriptTags(self : BLFontFaceCore*, out : BLArrayCore*) : BLResult
    fun blFontFaceGetFeatureTags(self : BLFontFaceCore*, out : BLArrayCore*) : BLResult
    fun blFontFaceGetVariationTags(self : BLFontFaceCore*, out : BLArrayCore*) : BLResult

    enum BLFontFaceFlags : UInt32
      NoFlags            =          0
      TypographicNames   =          1
      TypographicMetrics =          2
      CharToGlyphMapping =          4
      HorizontalMetircs  =         16
      VerticalMetrics    =         32
      HorizontalKerning  =         64
      VerticalKerning    =        128
      OpentypeFeatures   =        256
      PanoseData         =        512
      UnicodeCoverage    =       1024
      BaselineYEquals0   =       4096
      LsbPointXEquals0   =       8192
      VariationSequences =  268435456
      OpentypeVariations =  536870912
      SymbolFont         = 1073741824
      LastResortFont     = 2147483648
    end

    enum BLFontFaceDiagFlags : UInt32
      NoFlags         =  0
      WrongNameData   =  1
      IxedNameData    =  2
      WrongKernData   =  4
      IxedKernData    =  8
      WrongCmapData   = 16
      WrongCmapFormat = 32
    end

    enum BLFontOutlineType : UInt32
      None     = 0
      Truetype = 1
      Cff      = 2
      Cff2     = 3
    end

    struct BLFontFaceInfo
      face_type : UInt8
      outline_type : UInt8
      reserved8 : UInt8[2]
      glyph_count : UInt32
      revision : UInt32
      face_index : UInt32
      face_flags : UInt32
      diag_flags : UInt32
      reserved : UInt32[2]
    end

    struct BLFontFaceCore
      _d : BLFontFaceImpl*
    end

    struct BLFontFaceVirt
      base : BLObjectVirtBase
    end

    struct BLFontFaceImpl
      virt : BLFontFaceVirt*
      weight : UInt16
      stretch : UInt8
      style : UInt8
      face_info : BLFontFaceInfo
      unique_id : BLUniqueId
      data : BLFontDataCore
      full_name : BLStringCore
      family_name : BLStringCore
      subfamily_name : BLStringCore
      post_script_name : BLStringCore
      design_metrics : BLFontDesignMetrics
      unicode_coverage : BLFontUnicodeCoverage
      panose : BLFontPanose
    end
  end
end
