# This file is automatically generated and should not be manually edited

module Blend2D
  @[Link("blend2d")]
  lib LibBlend2D
    fun blFormatInfoQuery(self : BLFormatInfo*, format : BLFormat) : BLResult
    fun blFormatInfoSanitize(self : BLFormatInfo*) : BLResult

    enum BLFormat : UInt32
      None   = 0
      Prgb32 = 1
      Xrgb32 = 2
      A8     = 3
    end

    enum BLFormatFlags : UInt32
      NoFlags       =      0
      RGB           =      1
      Alpha         =      2
      RGBA          =      3
      Lum           =      4
      Luma          =      6
      Indexed       =     16
      Premultiplied =    256
      ByteSwap      =    512
      ByteAligned   =  65536
      UndefinedBits = 131072
      LE            =      0
      BE            =    512
    end

    struct BLFormatInfo
      depth : UInt32
      flags : BLFormatFlags
      palette : BLRgba32*
    end
  end
end
