# This file is automatically generated and should not be manually edited

module Blend2D
  @[Link("blend2d")]
  lib LibBlend2D
    enum BLGeometryDirection : UInt32
      None = 0
      CW   = 1
      CCW  = 2
    end

    enum BLGeometryType : UInt32
      None           =  0
      Boxi           =  1
      Boxd           =  2
      Recti          =  3
      Rectd          =  4
      Circle         =  5
      Ellipse        =  6
      RoundRect      =  7
      Arc            =  8
      Chord          =  9
      Pie            = 10
      Line           = 11
      Triangle       = 12
      Polylinei      = 13
      Polylined      = 14
      Polygoni       = 15
      Polygond       = 16
      ArrayViewBoxi  = 17
      ArrayViewBoxd  = 18
      ArrayViewRecti = 19
      ArrayViewRectd = 20
      Path           = 21
      SimpleLast     = 12
    end

    enum BLFillRule : UInt32
      NonZero = 0
      EvenOdd = 1
    end

    enum BLHitTest : UInt32
      In      =          0
      Part    =          1
      Out     =          2
      Invalid = 4294967295
    end

    struct BLPointI
      x : Int32
      y : Int32
    end

    struct BLSizeI
      w : Int32
      h : Int32
    end

    struct BLBoxI
      x0 : Int32
      y0 : Int32
      x1 : Int32
      y1 : Int32
    end

    struct BLRectI
      x : Int32
      y : Int32
      w : Int32
      h : Int32
    end

    struct BLPoint
      x : Float64
      y : Float64
    end

    struct BLSize
      w : Float64
      h : Float64
    end

    struct BLBox
      x0 : Float64
      y0 : Float64
      x1 : Float64
      y1 : Float64
    end

    struct BLRect
      x : Float64
      y : Float64
      w : Float64
      h : Float64
    end

    struct BLLine
      x0 : Float64
      y0 : Float64
      x1 : Float64
      y1 : Float64
    end

    struct BLTriangle
      x0 : Float64
      y0 : Float64
      x1 : Float64
      y1 : Float64
      x2 : Float64
      y2 : Float64
    end

    struct BLRoundRect
      x : Float64
      y : Float64
      w : Float64
      h : Float64
      rx : Float64
      ry : Float64
    end

    struct BLCircle
      cx : Float64
      cy : Float64
      r : Float64
    end

    struct BLEllipse
      cx : Float64
      cy : Float64
      rx : Float64
      ry : Float64
    end

    struct BLArc
      cx : Float64
      cy : Float64
      rx : Float64
      ry : Float64
      start : Float64
      sweep : Float64
    end
  end
end
