# This file is automatically generated and should not be manually edited

module Blend2D
  @[Link("blend2d")]
  lib LibBlend2D
    enum BLGlyphRunFlags : UInt32
      NoFlags         =          0
      Ucs4Content     =  268435456
      InvalidText     =  536870912
      UndefinedGlyphs = 1073741824
      InvalidFontData = 2147483648
    end

    enum BLGlyphPlacementType : UInt32
      None          = 0
      AdvanceOffset = 1
      DesignUnits   = 2
      UserUnits     = 3
      AbsoluteUnits = 4
    end

    struct BLGlyphRun
      glyph_data : Void*
      placement_data : Void*
      size : Int32
      reserved : UInt8
      placement_type : UInt8
      glyph_advance : UInt8
      placement_advance : UInt8
      flags : UInt32
    end
  end
end
