# This file is automatically generated and should not be manually edited

module Blend2D
  @[Link("blend2d")]
  lib LibBlend2D
    fun blImageDecoderInit(self : BLImageDecoderCore*) : BLResult
    fun blImageDecoderInitMove(self : BLImageDecoderCore*, other : BLImageDecoderCore*) : BLResult
    fun blImageDecoderInitWeak(self : BLImageDecoderCore*, other : BLImageDecoderCore*) : BLResult
    fun blImageDecoderDestroy(self : BLImageDecoderCore*) : BLResult
    fun blImageDecoderReset(self : BLImageDecoderCore*) : BLResult
    fun blImageDecoderAssignMove(self : BLImageDecoderCore*, other : BLImageDecoderCore*) : BLResult
    fun blImageDecoderAssignWeak(self : BLImageDecoderCore*, other : BLImageDecoderCore*) : BLResult
    fun blImageDecoderRestart(self : BLImageDecoderCore*) : BLResult
    fun blImageDecoderReadInfo(self : BLImageDecoderCore*, info_out : BLImageInfo*, data : UInt8*, size : Int32) : BLResult
    fun blImageDecoderReadFrame(self : BLImageDecoderCore*, image_out : BLImageCore*, data : UInt8*, size : Int32) : BLResult

    struct BLImageDecoderVirt
      base : BLObjectVirtBase
      restart : (BLImageDecoderImpl*) -> BLResult*
      read_info : (BLImageDecoderImpl*, BLImageInfo*, UInt8*, Int32) -> BLResult*
      read_frame : (BLImageDecoderImpl*, BLImageCore*, UInt8*, Int32) -> BLResult*
    end

    struct BLImageDecoderImpl
      virt : BLImageDecoderVirt*
      codec : BLImageCodecCore
      last_result : BLResult
      handle : Void*
      frame_index : LibC::ULong
      buffer_index : Int32
    end

    struct BLImageDecoderCore
      _d : BLImageDecoderImpl*
    end
  end
end
