# This file is automatically generated and should not be manually edited

module Blend2D
  @[Link("blend2d")]
  lib LibBlend2D
    fun blImageCodecInit(self : BLImageCodecCore*) : BLResult
    fun blImageCodecInitMove(self : BLImageCodecCore*, other : BLImageCodecCore*) : BLResult
    fun blImageCodecInitWeak(self : BLImageCodecCore*, other : BLImageCodecCore*) : BLResult
    fun blImageCodecInitByName(self : BLImageCodecCore*, name : UInt8*, size : LibC::ULong, codecs : BLArrayCore*) : BLResult
    fun blImageCodecDestroy(self : BLImageCodecCore*) : BLResult
    fun blImageCodecReset(self : BLImageCodecCore*) : BLResult
    fun blImageCodecAssignMove(self : BLImageCodecCore*, other : BLImageCodecCore*) : BLResult
    fun blImageCodecAssignWeak(self : BLImageCodecCore*, other : BLImageCodecCore*) : BLResult
    fun blImageCodecFindByName(self : BLImageCodecCore*, name : UInt8*, size : LibC::ULong, codecs : BLArrayCore*) : BLResult
    fun blImageCodecFindByExtension(self : BLImageCodecCore*, name : UInt8*, size : LibC::ULong, codecs : BLArrayCore*) : BLResult
    fun blImageCodecFindByData(self : BLImageCodecCore*, data : Void*, size : LibC::ULong, codecs : BLArrayCore*) : BLResult
    fun blImageCodecInspectData(self : BLImageCodecCore*, data : Void*, size : LibC::ULong) : UInt32
    fun blImageCodecCreateDecoder(self : BLImageCodecCore*, dst : BLImageDecoderCore*) : BLResult
    fun blImageCodecCreateEncoder(self : BLImageCodecCore*, dst : BLImageEncoderCore*) : BLResult
    fun blImageCodecArrayInitBuiltInCodecs(self : BLArrayCore*) : BLResult
    fun blImageCodecArrayAssignBuiltInCodecs(self : BLArrayCore*) : BLResult
    fun blImageCodecAddToBuiltIn(codec : BLImageCodecCore*) : BLResult
    fun blImageCodecRemoveFromBuiltIn(codec : BLImageCodecCore*) : BLResult

    enum BLImageCodecFeatures : UInt32
      NoFeatures =          0
      Read       =          1
      Write      =          2
      Lossless   =          4
      Lossy      =          8
      MultiFrame =         16
      Iptc       =  268435456
      Exif       =  536870912
      Xmp        = 1073741824
    end

    struct BLImageCodecCore
      _d : BLImageCodecImpl*
    end

    struct BLImageCodecVirt
      base : BLObjectVirtBase
      inspect_data : (BLImageCodecImpl*, UInt8*, LibC::ULong) -> UInt32*
      create_decoder : (BLImageCodecImpl*, BLImageDecoderCore*) -> BLResult*
      create_encoder : (BLImageCodecImpl*, BLImageEncoderCore*) -> BLResult*
    end

    struct BLImageCodecImpl
      virt : BLImageCodecVirt*
      name : BLStringCore
      vendor : BLStringCore
      mime_type : BLStringCore
      extensions : BLStringCore
      features : UInt32
    end
  end
end
