# This file is automatically generated and should not be manually edited

module Blend2D
  @[Link("blend2d")]
  lib LibBlend2D
    fun blMatrix2DSetIdentity(self : BLMatrix2D*) : BLResult
    fun blMatrix2DSetTranslation(self : BLMatrix2D*, x : Float64, y : Float64) : BLResult
    fun blMatrix2DSetScaling(self : BLMatrix2D*, x : Float64, y : Float64) : BLResult
    fun blMatrix2DSetSkewing(self : BLMatrix2D*, x : Float64, y : Float64) : BLResult
    fun blMatrix2DSetRotation(self : BLMatrix2D*, angle : Float64, cx : Float64, cy : Float64) : BLResult
    fun blMatrix2DApplyOp(self : BLMatrix2D*, op_type : BLTransformOp, op_data : Void*) : BLResult
    fun blMatrix2DInvert(dst : BLMatrix2D*, src : BLMatrix2D*) : BLResult
    fun blMatrix2DGetType(self : BLMatrix2D*) : BLTransformType
    fun blMatrix2DMapPointDArray(self : BLMatrix2D*, dst : BLPoint*, src : BLPoint*, count : Int32) : BLResult

    enum BLTransformType : UInt32
      Identity  = 0
      Translate = 1
      Scale     = 2
      Swap      = 3
      Affine    = 4
      Invalid   = 5
    end

    enum BLTransformOp : UInt32
      Reset         =  0
      Assign        =  1
      Translate     =  2
      Scale         =  3
      Skew          =  4
      Rotate        =  5
      RotatePt      =  6
      Transform     =  7
      PostTranslate =  8
      PostScale     =  9
      PostSkew      = 10
      PostRotate    = 11
      PostRotatePt  = 12
      PostTransform = 13
    end

    struct BLMatrix2D
      m00 : Float64
      m01 : Float64
      m10 : Float64
      m11 : Float64
      m20 : Float64
      m21 : Float64
    end
  end
end
