# This file is automatically generated and should not be manually edited

module Blend2D
  @[Link("blend2d")]
  lib LibBlend2D
    fun blPatternInit(self : BLPatternCore*) : BLResult
    fun blPatternInitMove(self : BLPatternCore*, other : BLPatternCore*) : BLResult
    fun blPatternInitWeak(self : BLPatternCore*, other : BLPatternCore*) : BLResult
    fun blPatternInitAs(self : BLPatternCore*, image : BLImageCore*, area : BLRectI*, extend_mode : BLExtendMode, transform : BLMatrix2D*) : BLResult
    fun blPatternDestroy(self : BLPatternCore*) : BLResult
    fun blPatternReset(self : BLPatternCore*) : BLResult
    fun blPatternAssignMove(self : BLPatternCore*, other : BLPatternCore*) : BLResult
    fun blPatternAssignWeak(self : BLPatternCore*, other : BLPatternCore*) : BLResult
    fun blPatternAssignDeep(self : BLPatternCore*, other : BLPatternCore*) : BLResult
    fun blPatternCreate(self : BLPatternCore*, image : BLImageCore*, area : BLRectI*, extend_mode : BLExtendMode, transform : BLMatrix2D*) : BLResult
    fun blPatternGetImage(self : BLPatternCore*, image : BLImageCore*) : BLResult
    fun blPatternSetImage(self : BLPatternCore*, image : BLImageCore*, area : BLRectI*) : BLResult
    fun blPatternResetImage(self : BLPatternCore*) : BLResult
    fun blPatternGetArea(self : BLPatternCore*, area_out : BLRectI*) : BLResult
    fun blPatternSetArea(self : BLPatternCore*, area : BLRectI*) : BLResult
    fun blPatternResetArea(self : BLPatternCore*) : BLResult
    fun blPatternGetExtendMode(self : BLPatternCore*) : BLExtendMode
    fun blPatternSetExtendMode(self : BLPatternCore*, extend_mode : BLExtendMode) : BLResult
    fun blPatternGetTransform(self : BLPatternCore*, transform_out : BLMatrix2D*) : BLResult
    fun blPatternGetTransformType(self : BLPatternCore*) : BLTransformType
    fun blPatternApplyTransformOp(self : BLPatternCore*, op_type : BLTransformOp, op_data : Void*) : BLResult
    fun blPatternEquals(a : BLPatternCore*, b : BLPatternCore*) : Int32

    enum BLPatternQuality : UInt32
      Nearest  = 0
      Bilinear = 1
    end

    struct BLPatternCore
      _d : BLPatternImpl*
    end

    struct BLPatternImpl
      image : BLImageCore
      area : BLRectI
      transform : BLMatrix2D
    end
  end
end
