# This file is automatically generated and should not be manually edited

module Blend2D
  @[Link("blend2d")]
  lib LibBlend2D
    alias BLPixelConverterFunc = (BLPixelConverterCore*, UInt8*, LibC::Long, UInt8*, LibC::Long, UInt32, UInt32, BLPixelConverterOptions*) -> BLResult*

    fun blPixelConverterInit(self : BLPixelConverterCore*) : BLResult
    fun blPixelConverterInitWeak(self : BLPixelConverterCore*, other : BLPixelConverterCore*) : BLResult
    fun blPixelConverterDestroy(self : BLPixelConverterCore*) : BLResult
    fun blPixelConverterReset(self : BLPixelConverterCore*) : BLResult
    fun blPixelConverterAssign(self : BLPixelConverterCore*, other : BLPixelConverterCore*) : BLResult
    fun blPixelConverterCreate(self : BLPixelConverterCore*, dst_info : BLFormatInfo*, src_info : BLFormatInfo*, create_flags : BLPixelConverterCreateFlags) : BLResult
    fun blPixelConverterConvert(self : BLPixelConverterCore*, dst_data : Void*, dst_stride : LibC::Long, src_data : Void*, src_stride : LibC::Long, w : UInt32, h : UInt32, options : BLPixelConverterOptions*) : BLResult

    enum BLPixelConverterCreateFlags : UInt32
      NoFlags          = 0
      DontCopyPalette  = 1
      AlterablePalette = 2
      NoMultiStep      = 4
    end

    struct BLPixelConverterOptions
      origin : BLPointI
      gap : LibC::ULong
    end

    struct BLPixelConverterCore
      data : UInt8[80]
    end
  end
end
