# This file is automatically generated and should not be manually edited

module Blend2D
  @[Link("blend2d")]
  lib LibBlend2D
    struct BLRgba32
      value : UInt32
    end

    struct BLRgba64
      value : LibC::ULong
    end

    struct BLRgba
      r : Float32
      g : Float32
      b : Float32
      a : Float32
    end
  end
end
