# This file is automatically generated and should not be manually edited

module Blend2D
  @[Link("blend2d")]
  lib LibBlend2D
    fun blRuntimeScopeBegin(self : BLRuntimeScopeCore*) : BLResult
    fun blRuntimeScopeEnd(self : BLRuntimeScopeCore*) : BLResult
    fun blRuntimeScopeIsActive(self : BLRuntimeScopeCore*) : Bool

    struct BLRuntimeScopeCore
      data : UInt32[2]
    end
  end
end
