# This file is automatically generated and should not be manually edited

module Blend2D
  @[Link("blend2d")]
  lib LibBlend2D
    fun blVarInitType(self : BLUnknown*, type : BLObjectType) : BLResult
    fun blVarInitNull(self : BLUnknown*) : BLResult
    fun blVarInitBool(self : BLUnknown*, value : Bool) : BLResult
    fun blVarInitInt32(self : BLUnknown*, value : Int32) : BLResult
    fun blVarInitInt64(self : BLUnknown*, value : LibC::Long) : BLResult
    fun blVarInitUInt32(self : BLUnknown*, value : UInt32) : BLResult
    fun blVarInitUInt64(self : BLUnknown*, value : LibC::ULong) : BLResult
    fun blVarInitDouble(self : BLUnknown*, value : Float64) : BLResult
    fun blVarInitRgba(self : BLUnknown*, rgba : BLRgba*) : BLResult
    fun blVarInitRgba32(self : BLUnknown*, rgba32 : UInt32) : BLResult
    fun blVarInitRgba64(self : BLUnknown*, rgba64 : LibC::ULong) : BLResult
    fun blVarInitMove(self : BLUnknown*, other : BLUnknown*) : BLResult
    fun blVarInitWeak(self : BLUnknown*, other : BLUnknown*) : BLResult
    fun blVarDestroy(self : BLUnknown*) : BLResult
    fun blVarReset(self : BLUnknown*) : BLResult
    fun blVarAssignNull(self : BLUnknown*) : BLResult
    fun blVarAssignBool(self : BLUnknown*, value : Bool) : BLResult
    fun blVarAssignInt32(self : BLUnknown*, value : Int32) : BLResult
    fun blVarAssignInt64(self : BLUnknown*, value : LibC::Long) : BLResult
    fun blVarAssignUInt32(self : BLUnknown*, value : UInt32) : BLResult
    fun blVarAssignUInt64(self : BLUnknown*, value : LibC::ULong) : BLResult
    fun blVarAssignDouble(self : BLUnknown*, value : Float64) : BLResult
    fun blVarAssignRgba(self : BLUnknown*, rgba : BLRgba*) : BLResult
    fun blVarAssignRgba32(self : BLUnknown*, rgba32 : UInt32) : BLResult
    fun blVarAssignRgba64(self : BLUnknown*, rgba64 : LibC::ULong) : BLResult
    fun blVarAssignMove(self : BLUnknown*, other : BLUnknown*) : BLResult
    fun blVarAssignWeak(self : BLUnknown*, other : BLUnknown*) : BLResult
    fun blVarGetType(self : BLUnknown*) : BLObjectType
    fun blVarToBool(self : BLUnknown*, out : Bool*) : BLResult
    fun blVarToInt32(self : BLUnknown*, out : Int32*) : BLResult
    fun blVarToInt64(self : BLUnknown*, out : LibC::Long*) : BLResult
    fun blVarToUInt32(self : BLUnknown*, out : UInt32*) : BLResult
    fun blVarToUInt64(self : BLUnknown*, out : LibC::ULong*) : BLResult
    fun blVarToDouble(self : BLUnknown*, out : Float64*) : BLResult
    fun blVarToRgba(self : BLUnknown*, out : BLRgba*) : BLResult
    fun blVarToRgba32(self : BLUnknown*, out : UInt32*) : BLResult
    fun blVarToRgba64(self : BLUnknown*, out : LibC::ULong*) : BLResult
    fun blVarEquals(a : BLUnknown*, b : BLUnknown*) : Bool
    fun blVarEqualsNull(self : BLUnknown*) : Bool
    fun blVarEqualsBool(self : BLUnknown*, value : Bool) : Bool
    fun blVarEqualsInt64(self : BLUnknown*, value : LibC::Long) : Bool
    fun blVarEqualsUInt64(self : BLUnknown*, value : LibC::ULong) : Bool
    fun blVarEqualsDouble(self : BLUnknown*, value : Float64) : Bool
    fun blVarEqualsRgba(self : BLUnknown*, rgba : BLRgba*) : Bool
    fun blVarEqualsRgba32(self : BLUnknown*, rgba32 : UInt32) : Bool
    fun blVarEqualsRgba64(self : BLUnknown*, rgba64 : LibC::ULong) : Bool
    fun blVarStrictEquals(a : BLUnknown*, b : BLUnknown*) : Bool

    struct BLVarCore
      _d : BLObjectDetail
    end
  end
end
